### ISSUE TITLE
LOL

### ISSUE THREAD

**Issue by master7720** [ThnksCJ/journeymap-1.12.2-5.7.1#1]

**Comment by ThnksCJ** [comment]
lmfao

**Comment by master7720** [comment]
whyd you do this xD

**Comment by master7720** [comment]
"tHerE gonNA sUe yOU"

**Comment by ThnksCJ** [comment]
its not obf or anything the code is readable so idk why i would get in trouble

**Comment by master7720** [comment]
> its not obf or anything the code is readable so idk why i would get in trouble

am clearly joking but ok
